<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>{{ $page['name'] }} · Sentinel Status</title><link rel="icon" href="/brand/sentinel.svg"><link rel="stylesheet" href="/css/sentinel.css"></head>
<body><header class="site-header"><a class="brand" href="/"><img src="/brand/sentinel.svg" width="38" height="38" alt=""><span>SENTINEL<small>SERVICE STATUS</small></span></a><span class="version-pill">PUBLIC STATUS</span></header>
<main id="main" class="status-main"><div class="eyebrow">SERVICE HEALTH</div><h1>{{ $page['name'] }}</h1><p class="muted">{{ $page['description'] }}</p>
<div class="status-banner state-{{ $page['status'] }}"><span class="status-dot"></span>{{ match($page['status']) { 'healthy' => 'All systems operational', 'down' => 'Service disruption', 'degraded' => 'Degraded performance', 'maintenance' => 'Maintenance in progress', default => 'Awaiting health data' } }}</div>
<section aria-labelledby="components-title"><h2 id="components-title">Components</h2><div class="component-list">@foreach($page['components'] as $component)<article class="component"><strong>{{ $component['name'] }}</strong><span class="uptime">{{ $component['uptime_percentage_24h'] !== null ? number_format($component['uptime_percentage_24h'], 3).'%' : '—' }} <small>uptime / 24h</small></span><span class="state-badge state-{{ $component['status'] }}">{{ ucfirst($component['status']) }}</span></article>@endforeach</div></section>
<section><h2>Recent incidents <small class="muted">Open and resolved in the last 7 days</small></h2>@forelse($page['incidents'] as $incident)<article class="status-entry"><span class="state-badge state-{{ $incident['status'] === 'open' ? 'down' : 'healthy' }}">{{ ucfirst($incident['status']) }}</span><h3>{{ $incident['component'] }}</h3><p>Started {{ \Carbon\Carbon::parse($incident['started_at'])->format('M j, Y H:i') }} UTC · Duration {{ round($incident['duration_seconds'] / 60, 1) }} minutes</p>@if($incident['resolved_at'])<p>Resolved {{ \Carbon\Carbon::parse($incident['resolved_at'])->format('M j, Y H:i') }} UTC</p>@endif</article>@empty<p class="empty-state">No recent incidents reported.</p>@endforelse</section>
<section><h2>Maintenance</h2>@forelse($page['maintenance'] as $window)<article class="status-entry"><span class="state-badge state-maintenance">{{ ucfirst($window['status']) }}</span><h3>{{ implode(', ', $window['components']) }}</h3><p>{{ \Carbon\Carbon::parse($window['start_at'])->format('M j, Y H:i') }} – {{ \Carbon\Carbon::parse($window['end_at'])->format('M j, Y H:i') }} UTC</p></article>@empty<p class="empty-state">No scheduled or recent maintenance.</p>@endforelse</section>
<p class="muted status-footnote">Updated {{ \Carbon\Carbon::parse($page['updated_at'])->format('H:i:s') }} UTC. Availability is based on recorded checks, excluding maintenance. Data may be cached for 30 seconds.</p></main>
<footer class="site-footer"><span>Powered by <a href="/">Sentinel</a></span><span>Service health, made visible.</span></footer></body></html>
